name: Cppcheck Static Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *' # Daily at 10:00 UTC
jobs:
  cppcheck:
    name: Cppcheck Static Analysis
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -y
          cppcheck
          libboost-filesystem-dev
          libboost-log-dev
          libboost-system-dev
          libboost-thread-dev
          libcurl4-openssl-dev
          libgoogle-perftools-dev
          libpcap-dev
          libtool
          libtool-bin
          libunwind-dev
          sip-tester
      - run: |
          set -x
          cppcheck --enable=warning,performance,portability,style --error-exitcode=1 src/
